package gml

type CustomAssetIndex int32

var (
	customAssetIndexToPath []string
)

func (index CustomAssetIndex) Path() string {
	i := int(index)
	if i >= len(customAssetIndexToPath) {
		return ""
	}
	return customAssetIndexToPath[i]
}

// InitCustomAsset is used by code generated by gmlgo so you can query a custom asset
func InitCustomAsset(indexToPath []string) {
	customAssetIndexToPath = indexToPath
}
