package gml

type CustomAssetIndex int32

var (
	customAssetIndexToPath []string
)

func (index CustomAssetIndex) Path() string {
	return customAssetIndexToPath[index]
}

// InitCustomAsset is used by code generated by gmlgo so you can query a custom asset
func InitCustomAsset(indexToPath []string) {
	customAssetIndexToPath = indexToPath
}
