language: go

go:
  - "1.12.5"

# https://restic.net/blog/2018-09-02/travis-build-cache
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - libglew-dev # required by headless-gl.
      - libgles2-mesa-dev
      - libalut-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev

services:
  - xvfb

install:
  - export GO111MODULE=on
  - go mod download
  - go get
  # Underlying framework used
  #- go get -t -v github.com/hajimehoshi/ebiten/...
  # Debug Mode: Live file reloading (watch files for changes)
  #- go get -t -v github.com/fsnotify/fsnotify/...

before_script:
  - export DISPLAY=:99.0

script:
  - go install -v -tags debug ./gml
  - go install -v -tags headless ./gml
  - go install -v -tags "debug headless" ./gml
  - go install -v ./gml
  - go install -v ./cmd/gmlgo
  - gmlgo generate -v ./examples/...
  - go build -tags debug -v ./examples/...
  - go build -tags headless -v ./examples/...
  - go build -tags "debug headless" -v ./examples/...
  - go build -v ./examples/...
  - go test -v ./gml/...
  - go test -tags debug -v ./gml/...
  - go test -tags headless -v ./gml/...
  - go test -tags "debug headless" -v ./gml/...
  - go test -v ./cmd/...
  - go test -tags "debug headless" -coverprofile="coverage_spaceship.out" -coverpkg=$(go list ./examples/spaceship/game) ./examples/spaceship/test
  - go test -tags "debug headless" -coverprofile="coverage_worm.out" -coverpkg=$(go list ./examples/worm/game) ./examples/worm/test
