language: go

go:
  - "1.10"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - libglew-dev # required by headless-gl.
      - libgles2-mesa-dev
      - libalut-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev

install:
  - go get -t -v github.com/hajimehoshi/ebiten/...
  - go get -t -v github.com/golang/protobuf/...

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - go build -v ./...
  - go build -tags debug -v ./...
  - go build -tags headless -v ./...
  # NOTE(Jake): 2018-06-20
  #
  # No tests exist yet
  #
  - go test -v ./...
  - go vet -v -composites=false ./...
