package game

import (
	"github.com/silbinarywolf/gml-go/cmd/gmlgo/testdata/serialization_private_error/game/sub"
	"github.com/silbinarywolf/gml-go/gml"
)

// ObjSerializablePrivate is generated by "gmlgo generate". DO NOT EDIT.
// Do not change this manually or you risk break connections made to this
// object, like in room files.
const ObjSerializablePrivate gml.ObjectIndex = 1266657269676769280

type SerializablePrivate struct {
	gml.Object
	gml.ObjectSerialize
	sub.Embed
}
